//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Educ8IT.AspNetCore.SimpleApi.HtmlDocumentation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Educ8IT.AspNetCore.SimpleApi.HtmlDocumentation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///    &lt;td class=&quot;api-name&quot;&gt;
        ///        &lt;a href=&quot;$$GUIDE_METHOD_URI$$&quot;&gt;($$HTTP_METHODS$$) $$METHOD_NAME$$&lt;/a&gt;
        ///    &lt;/td&gt;
        ///    &lt;td class=&quot;api-documentation&quot;&gt;
        ///        &lt;p&gt;$$METHOD_DESCRIPTION$$&lt;/p&gt;
        ///    &lt;/td&gt;
        ///&lt;/tr&gt;.
        /// </summary>
        internal static string ApiControllerMethodTemplate {
            get {
                return ResourceManager.GetString("ApiControllerMethodTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2 id=&quot;$$CONTROLLER_NAME$$&quot;&gt;&lt;a href=&quot;$$GUIDE_CONTROLLER_URI$$&quot;&gt;$$CONTROLLER_NAME$$&lt;/a&gt;&lt;/h2&gt;
        ///&lt;p&gt;$$CONTROLLER_DESCRIPTION$$&lt;/p&gt;
        ///&lt;table class=&quot;help-page-table&quot;&gt;
        ///    &lt;thead&gt;
        ///        &lt;tr&gt;
        ///            &lt;th&gt;Method&lt;/th&gt;
        ///            &lt;th&gt;Description&lt;/th&gt;
        ///        &lt;/tr&gt;
        ///    &lt;/thead&gt;
        ///    &lt;tbody&gt;
        ///        $$CONTROLLER_METHODS$$
        ///    &lt;/tbody&gt;
        ///&lt;/table&gt;
        ///.
        /// </summary>
        internal static string ApiControllerTemplate {
            get {
                return ResourceManager.GetString("ApiControllerTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;help-page-table&quot;&gt;
        ///    &lt;thead&gt;
        ///        &lt;tr&gt;
        ///            &lt;th&gt;Name&lt;/th&gt;
        ///            &lt;th&gt;Type&lt;/th&gt;
        ///        &lt;/tr&gt;
        ///    &lt;/thead&gt;
        ///    &lt;tbody&gt;
        ///        &lt;tr&gt;
        ///            &lt;td&gt;Key&lt;/td&gt;
        ///            &lt;td&gt;$$KEY_TYPE$$&lt;/td&gt;
        ///        &lt;/tr&gt;
        ///        &lt;tr&gt;
        ///            &lt;td&gt;Value&lt;/td&gt;
        ///            &lt;td&gt;$$VALUE_TYPE$$&lt;/td&gt;
        ///        &lt;/tr&gt;
        ///    &lt;/tbody&gt;
        ///&lt;/table&gt;.
        /// </summary>
        internal static string ApiDictionaryTypeTable {
            get {
                return ResourceManager.GetString("ApiDictionaryTypeTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;help-page-table&quot;&gt;
        ///    &lt;thead&gt;
        ///        &lt;tr&gt;
        ///            &lt;th&gt;Name&lt;/th&gt;
        ///            &lt;th&gt;Value&lt;/th&gt;
        ///            &lt;th&gt;Description&lt;/th&gt;
        ///        &lt;/tr&gt;
        ///    &lt;/thead&gt;
        ///    &lt;tbody&gt;
        ///        $$TABLE_ROWS$$
        ///    &lt;/tbody&gt;
        ///&lt;/table&gt;.
        /// </summary>
        internal static string ApiEnumTable {
            get {
                return ResourceManager.GetString("ApiEnumTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///    &lt;td class=&quot;enun-name&quot;&gt;$$ENUM_NAME$$&lt;/td&gt;
        ///    &lt;td class=&quot;enum-value&quot;&gt;$$ENUM_VALUE$$&lt;/td&gt;
        ///    &lt;td class=&quot;enum-description&quot;&gt;
        ///        &lt;p&gt;$$ENUM_DESCRIPTION$$&lt;/p&gt;
        ///    &lt;/td&gt;
        ///&lt;/tr&gt;
        ///.
        /// </summary>
        internal static string ApiEnumTableRow {
            get {
                return ResourceManager.GetString("ApiEnumTableRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///
        ///    &lt;h2&gt;&lt;a href=&quot;$$CONTOLLER_URI$$&quot;&gt;$$CONTROLLER_NAME$$&lt;/a&gt; : $$METHOD_NAME$$&lt;/h2&gt;
        ///    &lt;p&gt;$$METHOD_DESCRIPTION$$&lt;/p&gt;
        ///
        ///    &lt;h3&gt;Routes&lt;/h3&gt;
        ///    &lt;p&gt;$$ACTION_ROUTES$$&lt;/p&gt;
        ///
        ///    &lt;h2&gt;Authorisation Policies:&lt;/h2&gt;
        ///    &lt;p&gt;$$AUTH_POLICIES$$&lt;/p&gt;
        ///
        ///    &lt;h2&gt;Request Information&lt;/h2&gt;
        ///
        ///    &lt;h3&gt;Allowed Request Formats&lt;/h3&gt;
        ///    $$REQUEST_FORMATS$$
        ///
        ///    &lt;h3&gt;Header Parameters&lt;/h3&gt;
        ///    $$HEADER_PARAMETERS$$
        ///
        ///    &lt;h3&gt;Route Parameters&lt;/h3&gt;
        ///    $$ROUTE_PARAMETERS$$
        ///
        ///    &lt;h3&gt;Body Parameters&lt;/h3&gt;
        ///    $$BO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ApiMethodTemplate {
            get {
                return ResourceManager.GetString("ApiMethodTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head runat=&quot;server&quot;&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///
        ///    &lt;title&gt;$$PAGE_TITLE$$&lt;/title&gt;
        ///
        ///    &lt;!-- Latest compiled and minified CSS --&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css&quot; integrity=&quot;sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ApiPageTemplate {
            get {
                return ResourceManager.GetString("ApiPageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;help-page-table&quot;&gt;
        ///    &lt;thead&gt;
        ///        &lt;tr&gt;
        ///            &lt;th&gt;Code&lt;/th&gt;
        ///            &lt;th&gt;Description&lt;/th&gt;
        ///            &lt;th&gt;Type&lt;/th&gt;
        ///        &lt;/tr&gt;
        ///    &lt;/thead&gt;
        ///    &lt;tbody&gt;
        ///        $$TABLE_ROWS$$
        ///    &lt;/tbody&gt;
        ///&lt;/table&gt;.
        /// </summary>
        internal static string ApiResponseTypeTable {
            get {
                return ResourceManager.GetString("ApiResponseTypeTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///    &lt;td class=&quot;enun-name&quot;&gt;$$CODE$$&lt;/td&gt;
        ///    &lt;td class=&quot;enum-value&quot;&gt;$$DESCRIPTION$$&lt;/td&gt;
        ///    &lt;td class=&quot;enum-description&quot;&gt;$$TYPE$$&lt;/td&gt;
        ///&lt;/tr&gt;
        ///.
        /// </summary>
        internal static string ApiResponseTypeTableRow {
            get {
                return ResourceManager.GetString("ApiResponseTypeTableRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;$$TYPE_NAME$$&lt;/h2&gt;
        ///&lt;div&gt;
        ///    &lt;p&gt;
        ///        $$TYPE_DESCRIPTION$$
        ///    &lt;/p&gt;
        ///
        ///    $$TYPE_PROPERTIES$$
        ///&lt;/div&gt;.
        /// </summary>
        internal static string ApiType {
            get {
                return ResourceManager.GetString("ApiType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;help-page-table&quot;&gt;
        ///    &lt;thead&gt;
        ///        &lt;tr&gt;
        ///            &lt;th&gt;Name&lt;/th&gt;
        ///            &lt;th&gt;Description&lt;/th&gt;
        ///            &lt;th&gt;Type&lt;/th&gt;
        ///            &lt;th&gt;Additional information&lt;/th&gt;
        ///        &lt;/tr&gt;
        ///    &lt;/thead&gt;
        ///    &lt;tbody&gt;
        ///        $$TABLE_ROWS$$
        ///    &lt;/tbody&gt;
        ///&lt;/table&gt;.
        /// </summary>
        internal static string TypeTable {
            get {
                return ResourceManager.GetString("TypeTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///    &lt;td class=&quot;parameter-name&quot;&gt;$$PARAMETER_NAME$$&lt;/td&gt;
        ///    &lt;td class=&quot;parameter-documentation&quot;&gt;
        ///        &lt;p&gt;$$PARAMETER_DESCRIPTION$$&lt;/p&gt;
        ///    &lt;/td&gt;
        ///    &lt;td class=&quot;parameter-type&quot;&gt;
        ///        $$PARAMETER_TYPE$$
        ///    &lt;/td&gt;
        ///    &lt;td class=&quot;parameter-annotations&quot;&gt;
        ///        &lt;p&gt;$$PARAMETER_INFO$$&lt;/p&gt;
        ///    &lt;/td&gt;
        ///&lt;/tr&gt;
        ///.
        /// </summary>
        internal static string TypeTableRow {
            get {
                return ResourceManager.GetString("TypeTableRow", resourceCulture);
            }
        }
    }
}
